import { Inter } from 'next/font/google' 
import NavBar from './components/NavBar.js' 
import Btn from './components/Btn.js' 
import './globals.css'
import Link from 'next/link.js' 
import Post from './components/Post.js' 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <body>
      <div class="home-div"> 
        
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 
        <Post ImgSrc="/Hammaro.jpg" title="Gräsklippning" price="200" ></Post> 


      </div> 
      
    </body> 
  )
} 
